version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123
      - REDIS_PORT=6379
  static-ip-scrapping:
    build: .
    depends_on:
      - redis
    ports:
      - ${PORT}:${PORT}
    links:
      - redis
    environment:
      - REDIS_HOST=redis
volumes:
  dbdata:
